interface IonStyles {
  backdropOpacity?: number
  background?: any
  backgroundActivated?: any
  backgroundActivatedOpacity?: number
  backgroundChecked?: any
  backgroundFocused?: any
  backgroundFocusedOpacity?: number
  backgroundHover?: any
  backgroundHoverOpacity?: number
  backgroundRgb?: any
  barBackground?: any
  barBackgroundActive?: any
  barBorderRadius?: any
  barHeight?: any
  border?: any
  borderColor?: any
  borderColorChecked?: any
  borderRadius?: any
  borderStyle?: any
  borderWidth?: any
  boxShadow?: any
  bufferBackground?: any
  bulletBackground?: any
  bulletBackgroundActive?: any
  buttonBackground?: any
  buttonBackgroundActivated?: any
  buttonBackgroundActivatedOpacity?: number
  buttonBackgroundFocused?: any
  buttonBackgroundFocusedOpacity?: number
  buttonBackgroundHover?: any
  buttonBackgroundHoverOpacity?: number
  buttonBackgroundSelected?: any
  buttonBackgroundSelectedOpacity?: number
  buttonColor?: any
  buttonColorActivated?: any
  buttonColorFocused?: any
  buttonColorHover?: any
  buttonColorSelected?: any
  cancelButtonColor?: any
  checkmarkColor?: any
  checkmarkWidth?: any
  clearButtonColor?: any
  closeIconFontSize?: any
  color?: any
  colorActivated?: any
  colorChecked?: any
  colorFocused?: any
  colorHover?: any
  colorSelected?: any
  detailIconColor?: any
  detailIconFontSize?: any
  detailIconOpacity?: number
  end?: any
  handleBackground?: any
  handleBackgroundChecked?: any
  handleBorderRadius?: any
  handleBoxShadow?: any
  handleHeight?: any
  handleMaxHeight?: any
  handleSpacing?: any
  handleTransition?: any
  handleWidth?: any
  height?: any
  highlightColorFocused?: any
  highlightColorInvalid?: any
  highlightColorValid?: any
  highlightHeight?: any
  iconColor?: any
  iconFontSize?: any
  iconFontWeight?: any
  iconMarginBottom?: any
  iconMarginEnd?: any
  iconMarginStart?: any
  iconMarginTop?: any
  iconPaddingBottom?: any
  iconPaddingEnd?: any
  iconPaddingStart?: any
  iconPaddingTop?: any
  indicatorBoxShadow?: any
  indicatorColor?: any
  indicatorHeight?: any
  indicatorTransform?: any
  indicatorTransition?: any
  innerBorderRadius?: any
  innerBorderWidth?: any
  innerBoxShadow?: any
  innerPaddingBottom?: any
  innerPaddingEnd?: any
  innerPaddingStart?: any
  innerPaddingTop?: any
  ionGridColumnPadding?: any
  ionGridColumnPaddingLg?: any
  ionGridColumnPaddingMd?: any
  ionGridColumnPaddingSm?: any
  ionGridColumnPaddingXl?: any
  ionGridColumnPaddingXs?: any
  ionGridColumns?: any
  ionGridPadding?: any
  ionGridPaddingLg?: any
  ionGridPaddingMd?: any
  ionGridPaddingSm?: any
  ionGridPaddingXl?: any
  ionGridPaddingXs?: any
  ionGridWidth?: any
  ionGridWidthLg?: any
  ionGridWidthMd?: any
  ionGridWidthSm?: any
  ionGridWidthXl?: any
  ionGridWidthXs?: any
  keyboardOffset?: any
  knobBackground?: any
  knobBorderRadius?: any
  knobBoxShadow?: any
  knobSize?: any
  marginBottom?: any
  marginEnd?: any
  marginStart?: any
  marginTop?: any
  maxHeight?: any
  maxWidth?: any
  minHeight?: any
  minWidth?: any
  offsetBottom?: any
  offsetTop?: any
  opacity?: number
  paddingBottom?: any
  paddingEnd?: any
  paddingStart?: any
  paddingTop?: any
  pinBackground?: any
  pinColor?: any
  placeholderColor?: any
  placeholderFontStyle?: any
  placeholderFontWeight?: any
  placeholderOpacity?: number
  progressBackground?: any
  progressBarBackground?: any
  progressBarBackgroundActive?: any
  rippleColor?: any
  scrollBarBackground?: any
  scrollBarBackgroundActive?: any
  sideMaxWidth?: any
  sideMinWidth?: any
  sideWidth?: any
  size?: any
  start?: any
  spinnerColor?: any
  transition?: any
  whiteSpace?: any
  width?: any
}

export type IonButtonStyles = Pick<IonStyles, 'background' | 'backgroundActivated' | 'backgroundActivatedOpacity' | 'backgroundFocused' | 'backgroundFocusedOpacity' | 'backgroundHover' | 'backgroundHoverOpacity' | 'borderColor' | 'borderRadius' | 'borderStyle' | 'borderWidth' | 'boxShadow' | 'color' | 'colorActivated' | 'colorFocused' | 'colorHover' | 'opacity' | 'paddingBottom' | 'paddingEnd' | 'paddingStart' | 'paddingTop' | 'rippleColor' | 'transition'>;